package classes;

import java.time.ZoneId;

//TODO fully comment this class

/**
 * A class used as a serializable Time Zone
 * <br>
 * <br>
 * Serialized Value is generated by using {@link ZoneId#getId()}
 * 
 * @author Tealeaf
 * @see ZoneId
 */
public class TimeZone {

	private String id;

	private transient ZoneId zoneId;

	/**
	 * Creates a Time Zone object that defaults to the system default Time Zone
	 */
	public TimeZone() {
		setZone(ZoneId.systemDefault());
	}

	/**
	 * creates a Time Zone object with a given time zone
	 * 
	 * @param zoneId the {@link ZoneId Time Zone (ZoneId)} to use
	 */
	public TimeZone(ZoneId zoneId) {
		setZone(zoneId);
	}

	/**
	 * Gets the String ID representative of the Time Zone
	 * <br>
	 * <br>
	 * This value is generated by using {@link ZoneId#getId()}
	 * 
	 * @return String ID Representative
	 */
	public String getId() {
		return id;
	}

	/**
	 * Sets the String ID Representative of the Time Zone
	 * <br>
	 * <br>
	 * This value is generated by using {@link ZoneId#getId()}
	 * 
	 * @param id - String ID Representative
	 */
	public void setId(String id) {
		this.id = id;
	}

	public ZoneId getZone() {
		return (zoneId == null) ? (zoneId = ZoneId.of(id)) : zoneId;
	}

	public void setZone(ZoneId zoneId) {
		this.zoneId = zoneId;
		id = zoneId.getId();
	}

	public boolean equals(TimeZone timeZone) {
		return this.getId().contentEquals(timeZone.getId());
	}
}
